### ISSUE TITLE
generateproto issue

### ISSUE THREAD

**Issue by mustafayildirim93** [socotecio/django-socio-grpc#122]
Hi ! I hope its all going good for you.

I was searching about  [[django-grpc-framework](https://djangogrpcframework.readthedocs.io/en/latest/index.html)](url) and then i found out that there is some problems with that. I headed into your project.

I've got an error during step of 

`python manage.py generateproto`

 in your tutorial and full error i've got is 

`Traceback (most recent call last):
  File "/home/mustafa/.local/lib/python3.8/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'tutorial.urls' has no attribute 'grpc_handlers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mustafa/.local/lib/python3.8/site-packages/django_socio_grpc/settings.py", line 106, in import_from_string
    return import_string(val)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "tutorial.urls" does not define a "grpc_handlers" attribute/class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/mustafa/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django_socio_grpc/management/commands/generateproto.py", line 53, in handle
    grpc_settings.ROOT_HANDLERS_HOOK(None)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django_socio_grpc/settings.py", line 151, in __getattr__
    val = perform_import(val, attr)
  File "/home/mustafa/.local/lib/python3.8/site-packages/django_socio_grpc/settings.py", line 89, in perform_import
    return import_from_string(
  File "/home/mustafa/.local/lib/python3.8/site-packages/django_socio_grpc/settings.py", line 108, in import_from_string
    raise ImportError(
ImportError: Could not import 'tutorial.urls.grpc_handlers' for GRPC setting 'ROOT_HANDLERS_HOOK'. ImportError: Module "tutorial.urls" does not define a "grpc_handlers" attribute/class.`

I couldn't even figure out what it is. Thank you for your help in advance !

**Comment by legau** [comment]
Hi @mustafayildirim93 

The tutorial is indeed incorrect, I've fixed it in this PR https://github.com/socotecio/django-socio-grpc/pull/123/files you can look at it directly until it is merged

**Comment by AMontagu** [comment]
closing as answered. Please feel free to reopen if problem persist.
