### ISSUE TITLE
Bug: grpc_message:"Class ListProtoSerializer missing

### ISSUE THREAD

**Issue by ThanhLV97** [socotecio/django-socio-grpc#214]
```
with grpc.insecure_channel('localhost:8000') as channel:
     stub = apis_pb2_grpc.CustomUserControllerStub(channel)
     for user in stub.List(apis_pb2.CustomUserListResponse()):
         print(user, end='')
```
I run it with my server and follow all the steps in the documentation with the custom user model in my application.
Server: 
`python manage.py grpcrunaioserver 127.0.0.1:8000 --max-workers 1`

Client Logs:
`  File "<stdin>", line 3, in <module>
  File "/Users/ambition/workspaces/developer/projects/django_project/wowai/wowai/venv/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambition/workspaces/developer/projects/django_project/wowai/wowai/venv/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Class ListProtoSerializer missing "Meta.proto_class_list" attribute"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Class ListProtoSerializer missing \"Meta.proto_class_list\" attribute", grpc_status:2, created_time:"2023-11-19T10:19:21.600447+07:00"}"`/'

Server logs:

`AssertionError : Class ListProtoSerializer missing "Meta.proto_class_list" attribute
Traceback (most recent call last):
  File "/Users/ambition/workspaces/developer/projects/django_project/wowai/wowai/venv/lib/python3.11/site-packages/django_socio_grpc/utils/utils.py", line 33, in safe_async_response
    return await response
           ^^^^^^^^^^^^^^
  File "/Users/ambition/workspaces/developer/projects/django_project/wowai/wowai/venv/lib/python3.11/site-packages/django_socio_grpc/mixins.py", line 396, in List
    return await serializer.amessage
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambition/workspaces/developer/projects/django_project/wowai/wowai/venv/lib/python3.11/site-packages/django_socio_grpc/proto_serializers.py", line 78, in amessage
    self._message = self.data_to_message(await self.adata)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambition/workspaces/developer/projects/django_project/wowai/wowai/venv/lib/python3.11/site-packages/django_socio_grpc/proto_serializers.py", line 150, in data_to_message
    assert hasattr(
AssertionError: Class ListProtoSerializer missing "Meta.proto_class_list" attribute`

**Comment by ThanhLV97** [comment]
I closed this issue, because i forgot the step register service in my  custom application.
